# Generated by Django 5.1.7 on 2025-03-17 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio_operations', models.CharField(blank=True, max_length=255, null=True)),
                ('it_project_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('critical_project', models.BooleanField(default=False)),
                ('it_service_owner_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('business_sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('project_budget', models.CharField(blank=True, max_length=255, null=True)),
                ('business_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_finish_date', models.DateField(blank=True, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('business_value', models.TextField(blank=True, null=True)),
                ('roi', models.IntegerField(blank=True, null=True)),
                ('project_scope', models.TextField(blank=True, null=True)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('vendor_service_support', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
