# Generated by Django 5.1.7 on 2025-03-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectform_first_task_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='first_risk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='first_risk_mitigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='first_risk_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='first_risk_severity',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='first_risk_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='second_risk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='second_risk_mitigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='second_risk_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='second_risk_severity',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='second_risk_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='third_risk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='third_risk_mitigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='third_risk_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='third_risk_severity',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='third_risk_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
