# Generated by Django 5.1.7 on 2025-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectform_first_risk_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectform',
            name='first_risk_severity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectform',
            name='second_risk_severity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectform',
            name='third_risk_severity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
