# Generated by Django 5.1.7 on 2025-03-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectform_stack_first_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectform',
            old_name='first_risk_severity',
            new_name='first_risk_sevirity',
        ),
        migrations.RenameField(
            model_name='projectform',
            old_name='second_risk_severity',
            new_name='second_risk_sevirity',
        ),
        migrations.RenameField(
            model_name='projectform',
            old_name='third_risk_severity',
            new_name='third_risk_sevirity',
        ),
    ]
