# Generated by Django 5.1.7 on 2025-03-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_first_risk_severity_projectform_first_risk_sevirity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='c_plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='ms_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='project_report',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
