# Generated by Django 5.1.7 on 2025-05-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_projectform_business_name_projectform_business_sig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='it_pmo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
