# Generated by Django 5.1.7 on 2025-05-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projectform_it_pmo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectform',
            name='roi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
