# Generated by Django 5.1.7 on 2025-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projectform_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='dev_extra_date_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='dev_extra_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
