# Generated by Django 5.1.7 on 2025-06-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_projectform_dev_extra_date_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='task_duration_extra_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='task_ending_extra_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='task_name_extra_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='task_starting_extra_1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
