# Generated by Django 5.1.7 on 2025-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_projectform_task_duration_extra_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='risk_date_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_mitigation_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_sevirity_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_summary_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
