# Generated by Django 5.1.7 on 2025-06-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_projectform_risk_date_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='risk_date_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_date_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_mitigation_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_mitigation_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_name_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_sevirity_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_sevirity_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_summary_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='risk_summary_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
