# Generated by Django 5.1.7 on 2025-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_projectform_stack_department_extra_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='stack_department_extra_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='stack_name_extra_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='stack_role_extra_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
