# Generated by Django 5.1.7 on 2025-06-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_projectform_stack_department_extra_5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectform',
            name='c_plan',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=255, null=True),
        ),
    ]
