# Generated by Django 5.1.7 on 2025-06-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_it_business_name_projectform_it_business_partener_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='cl_actual_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_project_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
