# Generated by Django 5.1.7 on 2025-06-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_projectform_cl_actual_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='cl_reason_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_reason_status_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
