# Generated by Django 5.1.7 on 2025-06-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_projectform_cl_ana1_projectform_cl_ana2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='cl_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_business_name_sign',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_business_sponser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_business_sponser_sign',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_business_partener',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_business_partener_sig',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_pmo_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_pmo_manager_sig',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_project_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_project_manager_sig',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_service_owner_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_service_owner_manager_sig',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_technical_mgr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='cl_it_technical_mgr_sign',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
