# Generated by Django 5.1.7 on 2025-06-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_projectform_cl_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IT', 'IT'), ('Corporate', 'Corporate'), ('Operations', 'Operations'), ('Commercial', 'Commercial'), ('SBU', 'SBU'), ('Ground Operations', 'Ground Operations'), ('Technical Service', 'Technical Service')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='projectform',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.department'),
        ),
    ]
