# Generated by Django 5.1.7 on 2025-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_department_projectform_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('IT', 'IT'), ('Corporate', 'Corporate'), ('Operations', 'Operations'), ('Commercial', 'Commercial'), ('SBU', 'SBU'), ('Ground Operations', 'Ground Operations'), ('Technical Service', 'Technical Service')], max_length=100, unique=True),
        ),
    ]
