# Generated by Django 5.1.7 on 2025-06-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectform',
            name='ms_project',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectform',
            name='project_report',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=255, null=True),
        ),
    ]
