# Generated by Django 5.1.7 on 2025-06-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_projectform_ms_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectform',
            name='department',
        ),
    ]
