# Generated by Django 5.1.7 on 2025-06-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_projectform_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectform',
            name='it_project_manager_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectform',
            name='it_service_owner_manager_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
