# Generated by Django 5.1.7 on 2025-07-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_userdepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectform',
            old_name='project_name',
            new_name='main_project_name',
        ),
    ]
