# Generated by Django 5.1.7 on 2025-07-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_project_name_projectform_main_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectform',
            old_name='main_project_name',
            new_name='project_name',
        ),
    ]
