# Generated by Django 5.1.7 on 2025-07-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_main_project_name_projectform_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost10',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost11',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost12',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost13',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost14',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost15',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost7',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost8',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cost9',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name10',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name11',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name12',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name13',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name14',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name15',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name7',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name8',
        ),
        migrations.RemoveField(
            model_name='projectform',
            name='cl_cr_name9',
        ),
    ]
